export const config = {
  VITE_EMAIL_SERVICE_ID: import.meta.env.VITE_PROFILE_EMAILS_SERVICEID,
  VITE_EMAIL_TEMPLATE_ID: import.meta.env.VITE_PROFILE_EMAILS_TEMPLATEID,
  VITE_EMAIL_PUBLICK_EY: import.meta.env.VITE_PROFILE_EMAILS_PUBLIC_KEY,
};
